@startuml
!include https://raw.githubusercontent.com/adrianvlupu/C4-PlantUML/latest/C4_Container.puml

Person(opt, "Optometrist", "An optometrist who works with patients. Can be a supervisor or a student.")
System_Boundary(sv, "SuperVision") {
    Container(spa, "Single Page Application", "TypeScript and React", "Offline-first application that lets users manage patient data via their web browser.")
    ContainerDb(db, "Database", "PostgreSQL", "Stores user and patient data.")
    Container(api, "API Application", "TypeScript and NestJS", "Provides patient data manipulation/replication functionality via a GraphQL API.")
}
System_Ext(auth0, "Auth0 User Management", "Login Provider. Allows supervisors to manage accounts.")

Rel(opt, spa, "Manages patient data")
Rel(spa, auth0, "Redirect to login page", HTTPS)
Rel(auth0, spa, "Send user token", JWT)
Rel(api, auth0, "Verify user token", JWT)
Rel(spa, api, "Makes API calls to", GraphQL)
Rel(api, db, "Reads from and writes to", TypeORM)
@enduml
