apiVersion: v1
kind: Service
metadata:
  name: web-{{ include "helm.fullname" . }}
  labels: {{- include "helm.labels" . | nindent 4 }}
  annotations:
    cloud.google.com/network-tier: Standard
spec:
  type: NodePort
  ports:
    - port: 3333
      targetPort: 3333
      protocol: TCP
      name: http
  selector: {{- include "helm.selectorLabels" . | nindent 4 }}
