on:
  workflow_call:
    inputs:
      tags:
        required: true
      labels:
        required: true
      secrets:
        token:
          required: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: University-of-Auckland-SOFTENG761/supervision

jobs:
  build-push-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./apps/backend/Dockerfile
          push: true
          tags: ${{ inputs.tags }}
          labels: ${{ inputs.labels }}
